name: Wonderland DoorKnob CD

on:
  push:
    tags:
      - 'v*'

jobs:
  doorknob-authentication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build DoorKnob Authentication image
        run: |
          ./gradlew :doorknob-authentication:bootBuildImage -PimageTag=${GITHUB_REF#refs/tags/} -Dspring.profiles.active=production -PdockerToken=${{ secrets.DOCKER_TOKEN }}
          docker login -u ukonnra -p ${{ secrets.DOCKER_TOKEN }}
          docker tag docker.io/ukonnra/doorknob-authentication:${GITHUB_REF#refs/tags/} docker.io/ukonnra/doorknob-authentication:latest
          docker push docker.io/ukonnra/doorknob-authentication:latest
      - name: Deploy DoorKnob Authentication to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com
          docker tag docker.io/ukonnra/doorknob-authentication:latest registry.heroku.com/wonderland-doorknob/authentication:latest
          docker push registry.heroku.com/wonderland-doorknob/authentication:latest
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:release -a wonderland-doorknob web
